# Generated by Django 4.2.5 on 2023-09-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_remove_todo_file_comment'),
        ('user', '0002_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_todos',
            field=models.ManyToManyField(related_name='like_users', to='todo.todo'),
        ),
    ]
